---
services:
  opentelemetry-collector:
    image:  otel/opentelemetry-collector-contrib:0.114.0
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command: [ "--config=/etc/otel-collector-config.yml" ]
    depends_on:
      - tempo
      - loki
      - prometheus

  rust-http-metrics:
    image: rust-http-metrics
    container_name: rust-http-metrics
    build:
      dockerfile: Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4318
      RUST_LOG: debug
      OTEL_METRIC_EXPORT_INTERVAL: 10000
    depends_on:
      - opentelemetry-collector
    ports:
      - "8000:8000"

  tempo-init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    depends_on:
      - tempo-init

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-otlp-receiver
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml

  grafana:
    image: grafana/grafana:11.2.0
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    ports:
      - "3001:3000"

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
